-- San Antonio Zillow Housing Analysis
-- Raw staging table for the PostgreSQL ETL workflow
-- Purpose: Preserve the source CSV structure before validation and type conversion.

DROP TABLE IF EXISTS staging.zillow_analysis_raw;

CREATE TABLE staging.zillow_analysis_raw (
    zpid TEXT,
    palsid TEXT,
    id TEXT,
    rawhomestatuscd TEXT,
    marketingstatussimplifiedcd TEXT,
    imgsrC TEXT,
    hasimage TEXT,
    detailurl TEXT,
    statustype TEXT,
    statustext TEXT,
    countrycurrency TEXT,
    price TEXT,
    unformattedprice TEXT,
    address TEXT,
    addressstreet TEXT,
    addresscity TEXT,
    addressstate TEXT,
    addresszipcode TEXT,
    isundisclosedaddress TEXT,
    shouldshowrequestonprice TEXT,
    beds TEXT,
    baths TEXT,
    area TEXT,
    latlong TEXT,
    iszillowowned TEXT,
    flexfieldtext TEXT,
    contenttype TEXT,
    hdpdata TEXT,
    isuserclaimingowner TEXT,
    isuserconfirmedclaim TEXT,
    pgapt TEXT,
    sgapt TEXT,
    zestimate TEXT,
    shouldshowzestimateasprice TEXT,
    has3dmodel TEXT,
    hasvideo TEXT,
    ishomerec TEXT,
    hasadditionalattributions TEXT,
    isfeaturedlisting TEXT,
    isshowcaselisting TEXT,
    list TEXT,
    relaxed TEXT,
    info3string TEXT,
    info6string TEXT,
    brokername TEXT,
    carouselphotoscomposable TEXT,
    ispaidbuildernewconstruction TEXT,
    buildername TEXT,
    providerlistingid TEXT,
    hasopenhouse TEXT,
    openhousestartdate TEXT,
    openhouseenddate TEXT,
    openhousedescription TEXT,
    lotareastring TEXT,
    availabilitydate TEXT,
    daysonzillow TEXT,
    hometype TEXT,
    taxassessedvalue TEXT,
    lotareavalue TEXT,
    lotareaunit TEXT,
    pricechange TEXT,
    timeonzillow TEXT,
    lotareasqft TEXT,
    pricepersqft TEXT,
    haspricechange TEXT,
    pricequalityflag TEXT,
    logprice TEXT
);
